routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** @noinspection PhpUndefinedMethodInspection */
Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')
        ->name('home');

    /** @noinspection PhpUndefinedMethodInspection */
    Route::name('authorization')
        ->prefix('authorization')
        ->group(function () {
            Route::get('/', 'AuthorizationController@index');
            Route::get('{crm}', 'AuthorizationController@show')->name('.show');
            Route::get('{crm}/start', 'AuthorizationController@start')->name('.start');
            Route::get('{crm}/finish', 'AuthorizationController@finish')->name('.finish');
        });

    Route::resource('projects', 'ProjectController')
        ->except('show');
    Route::patch('projects/{project}/publish', 'ProjectController@publish')
        ->name('projects.publish');
    Route::get('projects/crm/{crm}', 'ProjectController@crm');

    Route::resource('projects.sites', 'SiteController')
        ->except('show');
    Route::patch('projects/{project}/sites/{site}/publish', 'SiteController@publish')
        ->name('projects.sites.publish');
    Route::match(['get', 'head'], 'projects/{project}/sites/import/create', 'SiteController@createImport')
        ->name('projects.sites.create_import');
    Route::post('projects/{project}/sites/import', 'SiteController@storeImport')
        ->name('projects.sites.store_import');
    Route::match(['get', 'head'], 'projects/{project}/sites/import/{site}/edit', 'SiteController@editImport')
        ->name('projects.sites.edit_import');
    Route::match(['put', 'patch'], 'projects/{project}/sites/import/{site}', 'SiteController@updateImport')
        ->name('projects.sites.update_import');

    Route::resource('projects.groups', 'GroupController')
        ->except('show');
    Route::patch('projects/{project}/groups/{group}/publish', 'GroupController@publish')
        ->name('projects.groups.publish');

    Route::resource('projects.applications', 'ApplicationController')
        ->only('index', 'show');

    Route::resource('projects.managers', 'ManagerController')
        ->except('show');
    Route::patch('projects/{project}/managers/{manager}/publish', 'ManagerController@publish')
        ->name('projects.managers.publish');

    Route::resource('sites.rules', 'RuleController')
        ->except('show');
    Route::patch('sites/{site}/rules/{rule}/publish', 'RuleController@publish')
        ->name('sites.rules.publish');
    Route::patch('sites/{site}/rules/{rule}/reorder', 'RuleController@reorder')
        ->name('sites.rules.reorder');

    Route::resource('users', 'UserController')
        ->except('show');
    Route::patch('users/{user}/publish', 'UserController@publish')
        ->name('users.publish');

    Route::get('projects/{project}/imports/pattern', 'ImportController@pattern')
        ->name('projects.imports.pattern');
    Route::resource('projects.imports', 'ImportController')
        ->except(['edit', 'update', 'destroy']);

    Route::resource('crm', 'CRMController')
        ->except('show');
    Route::get('crm/{crm}/settings', 'CRMController@editSettings')
        ->name('crm.edit_settings');
    Route::post('crm/{crm}/settings', 'CRMController@updateSettings')
        ->name('crm.save_settings');

    Route::get('urls-comments', 'UrlsCommentsController@list')
        ->name('urls-comments.index');
    Route::get('urls-comments/add', 'UrlsCommentsController@add')
        ->name('urls-comments.add');
    Route::post('urls-comments/add', 'UrlsCommentsController@store')
        ->name('urls-comments.store');
    Route::get('urls-comments/{urlsComment}/edit', 'UrlsCommentsController@editRecord')
        ->name('urls-comments.edit');
    Route::post('urls-comments/{urlsComment}/edit', 'UrlsCommentsController@editRecordPost')
        ->name('urls-comments.update');
    Route::delete('urls-comments/{urlsComment}/delete', 'UrlsCommentsController@deleteRecord')
        ->name('urls-comments.delete');

    Route::resource('projects.evecalls-imports', 'EveCalls\ImportController')
        ->except(['edit', 'update', 'destroy']);
});

Route::prefix('webhook')->group(function () {
    Route::post('contact-add', 'WebhookController@onContactAdded')
        ->name('webhook.contact.add');
    Route::post('survey', 'WebhookController@onSurveyReceived')
        ->name('webhook.survey');
});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Project
 * @package App\Models
 */
class Project extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'contact_identity',
        'crm_id',
        'lead_identity',
        'name',
        'publish',
        'moodle',
        'evecalls',
    ];

    /**
     * @var array
     */
    protected $casts = [
        'contact_identity' => 'integer',
        'lead_identity'    => 'integer',
        'crm_id'           => 'integer',
        'name'             => 'string',
        'publish'          => 'boolean',
        'moodle'           => 'array',
        'evecalls'         => 'array',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function crm()
    {
        return $this->belongsTo(CRM::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Bitrix\ClientFactory;
use App\Http\Requests\Project\PublishRequest;
use App\Http\Requests\Project\StoreRequest;
use App\Http\Requests\Project\UpdateRequest;
use App\Models\Application;
use App\Models\CRM;
use App\Models\Import;
use App\Models\Project;
use App\Models\Rule;
use App\Models\Site;
use App\Models\User;
use Bitrix24\CRM\Contact\UserField as ContactUserField;
use Bitrix24\CRM\Lead\UserField as LeadUserField;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Validator;

/**
 * Class ProjectController
 * @package App\Http\Controllers
 */
class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\View
     * @throws \Throwable
     */
    public function index()
    {
        try {
            /** @noinspection PhpDynamicAsStaticMethodCallInspection */
            $projects = Project::orderBy('name')->get();
        } catch (\Throwable $exception) {
            throw $exception;
        }

        return \View::make('project.index', [
            'projects' => $projects,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\View
     * @throws \Throwable
     */
    public function create()
    {
        if (Gate::denies('project.create')) {
            App::abort(403);
        }

        try {
            $collection = CRM::orderBy('name')->get();
        } catch (\Throwable $exception) {
            throw $exception;
        }

        return \View::make('project.create', [
            'collection' => $collection,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreRequest $request
     * @param \App\Helpers\Bitrix\ClientFactory $clientFactory
     * @return \Illuminate\Http\JsonResponse
     * @throws \Throwable
     */
    public function store(StoreRequest $request, ClientFactory $clientFactory)
    {
        $attributes = $request->validated();

        try {
            $this->validateIdentities($attributes, $clientFactory);
            $project = Project::create($attributes);
        } catch (\Throwable $exception) {
            throw $exception;
        }

        if (Gate::allows('project.update', [$project])) {
            $redirect = URL::route('projects.edit', ['project' => $project]);
        } else {
            $redirect = URL::route('projects.index');
        }

        return \Response::json(['redirect' => $redirect]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Project $project
     * @return void
     */
    public function show(Project $project)
    {
        throw new \BadMethodCallException('Method not implemented');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Project $project
     * @param \App\Helpers\Bitrix\ClientFactory $clientFactory
     * @return \Illuminate\Contracts\View\View
     * @throws \Throwable
     */
    public function edit(Project $project, ClientFactory $clientFactory)
    {
        if (Gate::denies('project.update', [$project])) {
            App::abort(403);
        }

        $contactIdentities = [];
        $leadIdentities = [];
        try {
            $collection = CRM::orderBy('name')->get();
            $crm = $project->crm;
            if ($crm instanceof CRM) {
                $contactIdentities = $this->getContactIdentityList($project->crm, $clientFactory);
                $leadIdentities = $this->getLeadIdentityList($project->crm, $clientFactory);
            }
        } catch (\Throwable $exception) {
            throw $exception;
        }

        return \View::make('project.edit', [
            'project' => $project,
            'collection' => $collection,
            'contactIdentities' => $contactIdentities,
            'leadIdentities' => $leadIdentities,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param  \App\Models\Project $project
     * @return void
     * @throws \Throwable
     */
    public function update(UpdateRequest $request, Project $project, ClientFactory $clientFactory)
    {
        $attributes = $request->validated();

        try {
            $this->validateIdentities($attributes, $clientFactory);
            $project->update($attributes);
        } catch (\Throwable $exception) {
            throw $exception;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Project $project
     * @return void
     * @throws \Throwable
     */
    public function destroy(Project $project)
    {
        if (Gate::denies('project.delete', [$project])) {
            App::abort(403);
        }

        try {
            /* Start delete imports */
            Import::whereHas('site', function (Builder $query) use ($project) {
                $query->where('project_id', $project->id);
            })->delete();
            /* End delete imports */

            /* Start delete users */
            $userIds = Import::select(['user_id'])
                ->distinct('user_id')
                ->getQuery()
                ->pluck('user_id');
            User::onlyTrashed()->whereNotIn('id', $userIds)->forceDelete();
            /* End delete users */

            /* Start delete sites */
            $siteIds = Application::select(['site_id'])
                ->distinct('site_id')
                ->getQuery()
                ->pluck('site_id');

            Site::whereProjectId($project->id)
                ->whereNotIn('id', $siteIds)
                ->forceDelete();

            Site::whereProjectId($project->id)->update(['publish' => false]);
            Rule::whereHas('site', function (Builder $query) use ($project) {
                $query->where('project_id', $project->id);
            })->delete();
            Site::whereProjectId($project->id)->delete();
            /* End delete sites */

            $project->delete();
        } catch (\Throwable $exception) {
            throw $exception;
        }
    }

    /**
     * @param PublishRequest $request
     * @param Project $project
     * @throws \Throwable
     */
    public function publish(PublishRequest $request, Project $project)
    {
        $publish = (bool) $request->input('publish');

        $project->publish = $publish;
        try {
            $project->saveOrFail();
        } catch (\Throwable $exception) {
            throw $exception;
        }
    }

    /**
     * @param \App\Models\CRM $crm
     * @param \App\Helpers\Bitrix\ClientFactory $clientFactory
     * @return \Illuminate\Http\JsonResponse
     * @throws \Throwable
     */
    public function crm(CRM $crm, ClientFactory $clientFactory)
    {
        if (! Auth::check()) {
            App::abort(403);
        }

        $data = [];
        try {
            $data['contactIdentities'] = $this->getContactIdentityList($crm, $clientFactory);
            $data['leadIdentities'] = $this->getLeadIdentityList($crm, $clientFactory);
        } catch (\Throwable $exception) {
            throw $exception;
        }

        return Response::json($data);
    }

    /**
     * @param array $attributes
     * @param \App\Helpers\Bitrix\ClientFactory $clientFactory
     * @throws \Throwable
     */
    private function validateIdentities(array $attributes, ClientFactory $clientFactory)
    {
        /** @var \App\Models\CRM $crm */
        try {
            $crm = CRM::findOrFail($attributes['crm_id']);
            $contactIdentities = $this->getContactIdentityList($crm, $clientFactory);
            $leadIdentities = $this->getLeadIdentityList($crm, $clientFactory);

            Validator::validate($attributes, [
                'contact_identity' => [
                    function ($attribute, $value, $fail) use ($contactIdentities) {
                        $data = Arr::first($contactIdentities, function ($data) use ($value) {
                            return ($data['id'] === (int)$value);
                        });

                        if (! is_array($data)) {
                            $fail('Invalid identity');
                        }
                    },
                ],
                'lead_identity' => [
                    function ($attribute, $value, $fail) use ($leadIdentities) {
                        $data = Arr::first($leadIdentities, function ($data) use ($value) {
                            return ($data['id'] === (int)$value);
                        });

                        if (! is_array($data)) {
                            $fail('Invalid identity');
                        }
                    },
                ]
            ]);
        } catch (\Throwable $exception) {
            throw $exception;
        }
    }

    /**
     * @param \App\Models\CRM $crm
     * @param \App\Helpers\Bitrix\ClientFactory $clientFactory
     * @return array
     * @throws \Throwable
     */
    private function getContactIdentityList(CRM $crm, ClientFactory $clientFactory)
    {
        try {
            $client = $clientFactory->create($crm);
        } catch (\Throwable $exception) {
            throw $exception;
        }

        $api = new ContactUserField($client);
        try {
            $id = Arr::get($crm->config, 'field.contact_identity');
            $result = $api->get($id);
        } catch (\Throwable $exception) {
            throw $exception;
        }

        $identityList = [];
        foreach (Arr::get($result,'result.LIST') as $data) {
            $id = (int) Arr::get($data, 'ID');
            $text = Arr::get($data, 'VALUE');

resources/views/project/create.blade.php
<?php
/** @var \Illuminate\Database\Eloquent\Collection|\App\Models\CRM[] $collection */
?>

@extends('layouts.start')

@section('start.title')Создание проекта@endsection

@section('start.content')
    <div class="content">
        <div class="choose-project row">
            <ul class="nav nav-pills justify-content-center col-12" id="tabSettings" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active show" id="settings_global-tab" data-toggle="tab" href="#settings_global"
                       role="tab" aria-controls="settings_global" aria-selected="true">
                        Глобальные настройки
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="settings_moodle-tab" data-toggle="tab" href="#settings_moodle" role="tab"
                       aria-controls="settings_moodle" aria-selected="false">
                        Настройки Moodle
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="settings_evecalls-tab" data-toggle="tab" href="#settings_evecalls"
                       role="tab"
                       aria-controls="settings_evecalls" aria-selected="false">
                        Настройки EVE.calls
                    </a>
                </li>
            </ul>
            <form id="admin-form" class="project-form" action="{{ route('projects.store') }}" method="post">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="settings_global" role="tabpanel"
                         aria-labelledby="settings_global-tab">
                        <h2>Создание проекта</h2>
                        <div class="form-group row">
                            <label for="name-input" class="col-sm-3 col-form-label">Название</label>
                            <div class="col-sm-9">
                                <input type="text" name="name" class="form-control"
                                       id="name-input" placeholder="Введите название проекта">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="crm-select" class="col-sm-3 col-form-label">CRM</label>
                            <div class="col-sm-9">
                                <select name="crm_id" id="crm-select" class="form-control">
                                    <option value="">-- Выберите значение --</option>
                                    @foreach($collection as $crm)
                                        <option value="{{ $crm->id }}">{{ $crm->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="contact_identity-select" class="col-sm-3 col-form-label">Идентификатор
                                контакта</label>
                            <div class="col-sm-9">
                                <select name="contact_identity" id="contact_identity-select" class="form-control"
                                        disabled>
                                    <option value="">-- Выберите значение --</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="lead_identity-select" class="col-sm-3 col-form-label">Идентификатор лида</label>
                            <div class="col-sm-9">
                                <select name="lead_identity" id="lead_identity-select" class="form-control" disabled>
                                    <option value="">-- Выберите значение --</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label" for="publish-input">Состояние</label>
                            <div class="col-sm-9">
                                <input type="hidden" name="publish" value="0">
                                <input type="checkbox" name="publish" value="1" id="publish-input"
                                       class="status-change">
                                <label class="form-control" for="publish-input"></label>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="settings_moodle" role="tabpanel"
                         aria-labelledby="settings_moodle-tab">
                        <h2>Настройки Moodle</h2>
                        <div class="form-group row">
                            <label for="moodle-url-input" class="col-sm-3 col-form-label">URL сайта Moodle</label>
                            <div class="col-sm-9">
                                <input type="url" name="moodle[base_url]" class="form-control" id="moodle-url-input"
                                       placeholder="Например, https://my.academyfx.ru">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="moodle-token-input" class="col-sm-3 col-form-label">Ключ доступа</label>
                            <div class="col-sm-9">
                                <input type="text" name="moodle[access_token]" class="form-control"
                                       id="moodle-token-input">
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="settings_evecalls" role="tabpanel"
                         aria-labelledby="settings_evecalls-tab">
                        <h2>Настройки EVE.calls</h2>
                        <div class="form-group row">
                            <label for="evecalls-api-key" class="col-sm-3 col-form-label">Ключ доступа API</label>
                            <div class="col-sm-9">
                                <input type="text" name="evecalls[api_key]" class="form-control"
                                       id="evecalls-api-key">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="evecalls-date-field-id" class="col-sm-3 col-form-label">ID поля "Дата звонка" в CRM</label>
                            <div class="col-sm-9">
                                <input type="text" name="evecalls[date_field]" class="form-control"
                                       placeholder="UF_CRM_XXXXXXXXXX"
                                       id="evecalls-date-field-id">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="evecalls-recording-field-id" class="col-sm-3 col-form-label">ID поля "Запись разговора" в CRM</label>
                            <div class="col-sm-9">
                                <input type="text" name="evecalls[recording_field]" class="form-control"
                                       placeholder="UF_CRM_XXXXXXXXXX"
                                       id="evecalls-recording-field-id">
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary">Создать</button>
                            <a href="{{ route('projects.index') }}" class="btn btn-secondary">Отмена</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/project/index.blade.php
<?php /** @var \Illuminate\Database\Eloquent\Collection|\App\Models\Project[] $projects */ ?>

@extends('layouts.start')

@section('start.title')Проекты@endsection

@section('start.content')
    <div class="choose-project">
        <ul class="list-group">
            <li class="list-group-item active">
                Проекты
                @can('project.create')
                    <a href="{{ route('projects.create') }}" class="btn btn-success">
                        Добавить проект
                    </a>
                @else
                    <span class="btn btn-secondary disabled">Добавить проект</span>
                @endcan
            </li>
            @foreach($projects as $project)
                <li id="project-{{ $project->id }}" class="list-group-item">
                    @can('project.update', [$project])
                        <input type="checkbox"
                               id="project-publish-{{ $project->id }}"
                               class="status-change ajax"
                               data-url="{{ route('projects.publish', $project) }}"
                               @if ($project->publish) checked @endif>
                        <label class="ajax" for="project-publish-{{ $project->id }}" data-name="{{ $project->name }}"></label>
                    @else
                        <input type="checkbox"
                               id="project-publish-{{ $project->id }}"
                               class="status-change"
                               disabled
                               @if ($project->publish) checked @endif>
                        <label for="project-publish-{{ $project->id }}"></label>
                    @endcan

                    @can('manager.list', [$project])
                        <a href="{{ route('projects.managers.index', ['project' => $project]) }}">{{ $project->name }}</a>
                    @elsecan('group.list', [$project])
                        <a href="{{ route('projects.groups.index', ['project' => $project]) }}">{{ $project->name }}</a>
                    @elsecan('site.list', [$project])
                        <a href="{{ route('projects.sites.index', ['project' => $project]) }}">{{ $project->name }}</a>
                    @elsecan('application.list', [$project])
                        <a href="{{ route('projects.applications.index', ['project' => $project]) }}">{{ $project->name }}</a>
                    @elsecan('import.list', [$project])
                        <a href="{{ route('projects.imports.index', ['project' => $project]) }}">{{ $project->name }}</a>
                    @else
                        <span class="text-secondary">{{ $project->name }}</span>
                    @endcan

                    <div class="btn-group" role="group">
                        @can('project.update', [$project])
                            <a href="{{ route('projects.edit', ['project' => $project]) }}" class="btn btn-outline-primary">
                                <i class="far fa-edit"></i>
                            </a>
                        @else
                            <span class="btn btn-outline-secondary disabled">
                                <i class="far fa-edit"></i>
                            </span>
                        @endcan

                        @can('project.delete', [$project])
                            <button type="button"
                                    class="btn btn-outline-danger ajax-delete"
                                    data-url="{{ route('projects.destroy', ['project' => $project]) }}"
                                    data-target="#project-{{ $project->id }}"
                                    data-name="{{ $project->name }}">
                                <i class="far fa-trash-alt"></i>
                            </button>
                        @else
                            <button type="button" class="btn btn-outline-secondary" disabled>
                                <i class="far fa-trash-alt"></i>
                            </button>
                        @endcan
                    </div>
                </li>
            @endforeach
        </ul>
    </div>
@endsection