routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** @noinspection PhpUndefinedMethodInspection */
Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')
        ->name('home');

    /** @noinspection PhpUndefinedMethodInspection */
    Route::name('authorization')
        ->prefix('authorization')
        ->group(function () {
            Route::get('/', 'AuthorizationController@index');
            Route::get('{crm}', 'AuthorizationController@show')->name('.show');
            Route::get('{crm}/start', 'AuthorizationController@start')->name('.start');
            Route::get('{crm}/finish', 'AuthorizationController@finish')->name('.finish');
        });

    Route::resource('projects', 'ProjectController')
        ->except('show');
    Route::patch('projects/{project}/publish', 'ProjectController@publish')
        ->name('projects.publish');
    Route::get('projects/crm/{crm}', 'ProjectController@crm');

    Route::resource('projects.sites', 'SiteController')
        ->except('show');
    Route::patch('projects/{project}/sites/{site}/publish', 'SiteController@publish')
        ->name('projects.sites.publish');
    Route::match(['get', 'head'], 'projects/{project}/sites/import/create', 'SiteController@createImport')
        ->name('projects.sites.create_import');
    Route::post('projects/{project}/sites/import', 'SiteController@storeImport')
        ->name('projects.sites.store_import');
    Route::match(['get', 'head'], 'projects/{project}/sites/import/{site}/edit', 'SiteController@editImport')
        ->name('projects.sites.edit_import');
    Route::match(['put', 'patch'], 'projects/{project}/sites/import/{site}', 'SiteController@updateImport')
        ->name('projects.sites.update_import');

    Route::resource('projects.groups', 'GroupController')
        ->except('show');
    Route::patch('projects/{project}/groups/{group}/publish', 'GroupController@publish')
        ->name('projects.groups.publish');

    Route::resource('projects.applications', 'ApplicationController')
        ->only('index', 'show');

    Route::resource('projects.managers', 'ManagerController')
        ->except('show');
    Route::patch('projects/{project}/managers/{manager}/publish', 'ManagerController@publish')
        ->name('projects.managers.publish');

    Route::resource('sites.rules', 'RuleController')
        ->except('show');
    Route::patch('sites/{site}/rules/{rule}/publish', 'RuleController@publish')
        ->name('sites.rules.publish');
    Route::patch('sites/{site}/rules/{rule}/reorder', 'RuleController@reorder')
        ->name('sites.rules.reorder');

    Route::resource('users', 'UserController')
        ->except('show');
    Route::patch('users/{user}/publish', 'UserController@publish')
        ->name('users.publish');

    Route::get('projects/{project}/imports/pattern', 'ImportController@pattern')
        ->name('projects.imports.pattern');
    Route::resource('projects.imports', 'ImportController')
        ->except(['edit', 'update', 'destroy']);

    Route::resource('crm', 'CRMController')
        ->except('show');
    Route::get('crm/{crm}/settings', 'CRMController@editSettings')
        ->name('crm.edit_settings');
    Route::post('crm/{crm}/settings', 'CRMController@updateSettings')
        ->name('crm.save_settings');

    Route::get('urls-comments', 'UrlsCommentsController@list')
        ->name('urls-comments.index');
    Route::get('urls-comments/add', 'UrlsCommentsController@add')
        ->name('urls-comments.add');
    Route::post('urls-comments/add', 'UrlsCommentsController@store')
        ->name('urls-comments.store');
    Route::get('urls-comments/{urlsComment}/edit', 'UrlsCommentsController@editRecord')
        ->name('urls-comments.edit');
    Route::post('urls-comments/{urlsComment}/edit', 'UrlsCommentsController@editRecordPost')
        ->name('urls-comments.update');
    Route::delete('urls-comments/{urlsComment}/delete', 'UrlsCommentsController@deleteRecord')
        ->name('urls-comments.delete');

    Route::resource('projects.evecalls-imports', 'EveCalls\ImportController')
        ->except(['edit', 'update', 'destroy']);
});

Route::prefix('webhook')->group(function () {
    Route::post('contact-add', 'WebhookController@onContactAdded')
        ->name('webhook.contact.add');
    Route::post('survey', 'WebhookController@onSurveyReceived')
        ->name('webhook.survey');
});

resources/views/evecalls-import/create.blade.php
<?php
/** @var \App\Models\Project $project */
?>

@extends('layouts.sidebar', ['project' => $project])

@section('sidebar.title')Создание импорта EVE.calls @endsection

@section('sidebar.breadcrumbs')
    <li class="breadcrumb-item">
        @can('evecalls-import.list', [$project])
            <a href="{{ route('projects.evecalls-imports.index', ['project' => $project]) }}">Импорты EVE.calls</a>
        @else
            <span class="text-white-50">Импорты EVE.calls</span>
        @endcan
    </li>
    <li class="breadcrumb-item active" aria-current="page">Создание импорта</li>
@endsection

@section('sidebar.content')
    <div class="content-header">
        <h3>Создание импорта</h3>
    </div>
    <div class="content-form">
        <form id="admin-form" action="{{ route('projects.evecalls-imports.store', ['project' => $project]) }}" method="post">
            <div class="form-group row">
                <label for="file-input" class="col-sm-2 col-form-label">Файл</label>
                <div class="col-sm-10">
                    <div>
                        <input type="file" name="file" id="file-input" class="form-control form-control-file" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label for="lead-name-input" class="col-sm-2 col-form-label">Название лида</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="lead_name" id="lead-name-input" placeholder="По умолчанию «{{ \App\Models\EveCalls\Import::DEFAULT_LEAD_NAME }}»">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Создать</button>
                    @can('evecalls-import.list', [$project])
                        <a href="{{ route('projects.evecalls-imports.index', ['project' => $project]) }}" class="btn">Отмена</a>
                    @else
                        <span class="btn disabled">Отмена</span>
                    @endcan
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/evecalls-import/index.blade.php
<?php
/** @var \App\Models\Project $project */
/** @var \Illuminate\Pagination\Paginator $paginator */
?>

@extends('layouts.sidebar', ['project' => $project])

@section('sidebar.title')Импорты EVE.calls @endsection

@section('sidebar.breadcrumbs')
    <li class="breadcrumb-item active" aria-current="page">Импорты EVE.calls</li>
@endsection

@section('sidebar.content')
    <div class="content-header">
        <h3>Список импортов</h3>
        @can('evecalls-import.create', [$project])
            <a href="{{ route('projects.evecalls-imports.create', ['project' => $project]) }}" class="btn btn-primary">Добавить импорт</a>
        @else
            <span class="btn btn-secondary disabled">Добавить импорт</span>
        @endcan
    </div>
    <div class="content-table">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Создан</th>
                    <th scope="col">Название лида</th>
                    <th scope="col">Пользователь</th>
                    <th scope="col">Состояние</th>
                    <th scope="col">Результат</th>
                    <th scope="col">ID</th>
                    <th scope="col">Действия</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($paginator->items() as $import)
                    <?php /** @var App\Models\EveCalls\Import $import */ ?>
                    <tr>
                        <td>
                            <span class="text-nowrap">{{ $import->created_at }}</span>
                        </td>
                        <td>
                            {{ $import->lead_name }}
                        </td>
                        <td>
                            @php $user = $import->user; @endphp
                            @if($user->trashed())
                                <s>{{ $user->name }}</s>
                            @else
                                <span>{{ $user->name }}</span>
                            @endif
                        </td>
                        <td>
                            @if($import->status === \App\Models\EveCalls\Import::PENDING_STATUS)
                                <span class="badge badge-secondary">Ожидание обработки</span>
                            @elseif($import->status === \App\Models\EveCalls\Import::PROCESSING_STATUS)
                                <span class="badge badge-primary">Обрабатывается</span>
                            @elseif($import->status === \App\Models\EveCalls\Import::COMPLETED_STATUS)
                                <span class="badge badge-success">Завершено</span>
                            @elseif($import->status === \App\Models\EveCalls\Import::ERROR_STATUS)
                                <a href="#"
                                   class="badge badge-danger"
                                   data-container="body"
                                   data-toggle="popover"
                                   data-trigger="focus"
                                   data-placement="left"
                                   data-content="{{ $import->error_text }}">Ошибка!</a>
                            @else
                                <span class="badge badge-warning">
                                    <i class="fas fa-exclamation-triangle fa-lg"></i>
                                    Неопределён
                                    <i class="fas fa-exclamation-triangle fa-lg"></i>
                                </span>
                            @endif
                        </td>
                        <td>
                            <span class="text-success">{{ $import->applications_count }}</span>
                            /
                            <span class="text-danger">{{ $import->errors_count }}</span>
                            /
                            {{ $import->applications_count + $import->errors_count}}
                        </td>
                        <th scope="row">{{ $import->id }}</th>
                        <td>
                            @can('evecalls-import.view', [$project, $import])
                                <a href="{{ route('projects.evecalls-imports.show', ['project' => $project, 'import' => $import]) }}" class="btn btn-outline-primary" target="_blank">
                                    <i class="far fa-eye"></i>
                                </a>
                            @else
                                <span class="btn btn-outline-secondary disabled">
                                    <i class="far fa-eye"></i>
                                </span>
                            @endcan
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    {{ $paginator->links() }}
@endsection

resources/views/evecalls-import/show.blade.php
<?php
/** @var \App\Models\Project $project */
/** @var \App\Models\EveCalls\Import $import */
/** @var \App\Models\Application[]|\App\Models\EveCalls\ImportError[] $rows */
?>

@extends('layouts.sidebar', ['project' => $project])

@section('sidebar.title')Просмотр импорта@endsection

@section('sidebar.breadcrumbs')
    <li class="breadcrumb-item">
        @can('evecalls-import.list', [$project])
            <a href="{{ route('projects.evecalls-imports.index', ['project' => $project]) }}">Импорты EVE.calls</a>
        @else
            <span class="text-white-50">Импорты</span>
        @endcan
    </li>
    <li class="breadcrumb-item active" aria-current="page">Результат импорта</li>
@endsection

@section('sidebar.content')
    <div class="content-header">
        <h3>Результат импорта #{{ $import->id }}</h3>
    </div>
    <div class="content-table">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" class="text-nowrap">Название лида</th>
                    <th scope="col">Телефон</th>
                    <th scope="col">Дата звонка</th>
                    <th scope="col">Запись разговора</th>
                </tr>
            </thead>
            <tbody>
                @foreach($import->applications as $row)
                    <tr class="table-success">
                        <th scope="col">{{ $row->id }}</th>
                        <td>{{ $row->form_name }}</td>
                        <td>{{ $row->sender_phone }}</td>
                        <td>{{ array_get($row->lead_extra_fields, $crm_date_field) }}</td>
                        <td>{{ array_get($row->lead_extra_fields, $crm_recording_field) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection