routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** @noinspection PhpUndefinedMethodInspection */
Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')
        ->name('home');

    /** @noinspection PhpUndefinedMethodInspection */
    Route::name('authorization')
        ->prefix('authorization')
        ->group(function () {
            Route::get('/', 'AuthorizationController@index');
            Route::get('{crm}', 'AuthorizationController@show')->name('.show');
            Route::get('{crm}/start', 'AuthorizationController@start')->name('.start');
            Route::get('{crm}/finish', 'AuthorizationController@finish')->name('.finish');
        });

    Route::resource('projects', 'ProjectController')
        ->except('show');
    Route::patch('projects/{project}/publish', 'ProjectController@publish')
        ->name('projects.publish');
    Route::get('projects/crm/{crm}', 'ProjectController@crm');

    Route::resource('projects.sites', 'SiteController')
        ->except('show');
    Route::patch('projects/{project}/sites/{site}/publish', 'SiteController@publish')
        ->name('projects.sites.publish');
    Route::match(['get', 'head'], 'projects/{project}/sites/import/create', 'SiteController@createImport')
        ->name('projects.sites.create_import');
    Route::post('projects/{project}/sites/import', 'SiteController@storeImport')
        ->name('projects.sites.store_import');
    Route::match(['get', 'head'], 'projects/{project}/sites/import/{site}/edit', 'SiteController@editImport')
        ->name('projects.sites.edit_import');
    Route::match(['put', 'patch'], 'projects/{project}/sites/import/{site}', 'SiteController@updateImport')
        ->name('projects.sites.update_import');

    Route::resource('projects.groups', 'GroupController')
        ->except('show');
    Route::patch('projects/{project}/groups/{group}/publish', 'GroupController@publish')
        ->name('projects.groups.publish');

    Route::resource('projects.applications', 'ApplicationController')
        ->only('index', 'show');

    Route::resource('projects.managers', 'ManagerController')
        ->except('show');
    Route::patch('projects/{project}/managers/{manager}/publish', 'ManagerController@publish')
        ->name('projects.managers.publish');

    Route::resource('sites.rules', 'RuleController')
        ->except('show');
    Route::patch('sites/{site}/rules/{rule}/publish', 'RuleController@publish')
        ->name('sites.rules.publish');
    Route::patch('sites/{site}/rules/{rule}/reorder', 'RuleController@reorder')
        ->name('sites.rules.reorder');

    Route::resource('users', 'UserController')
        ->except('show');
    Route::patch('users/{user}/publish', 'UserController@publish')
        ->name('users.publish');

    Route::get('projects/{project}/imports/pattern', 'ImportController@pattern')
        ->name('projects.imports.pattern');
    Route::resource('projects.imports', 'ImportController')
        ->except(['edit', 'update', 'destroy']);

    Route::resource('crm', 'CRMController')
        ->except('show');
    Route::get('crm/{crm}/settings', 'CRMController@editSettings')
        ->name('crm.edit_settings');
    Route::post('crm/{crm}/settings', 'CRMController@updateSettings')
        ->name('crm.save_settings');

    Route::get('urls-comments', 'UrlsCommentsController@list')
        ->name('urls-comments.index');
    Route::get('urls-comments/add', 'UrlsCommentsController@add')
        ->name('urls-comments.add');
    Route::post('urls-comments/add', 'UrlsCommentsController@store')
        ->name('urls-comments.store');
    Route::get('urls-comments/{urlsComment}/edit', 'UrlsCommentsController@editRecord')
        ->name('urls-comments.edit');
    Route::post('urls-comments/{urlsComment}/edit', 'UrlsCommentsController@editRecordPost')
        ->name('urls-comments.update');
    Route::delete('urls-comments/{urlsComment}/delete', 'UrlsCommentsController@deleteRecord')
        ->name('urls-comments.delete');

    Route::resource('projects.evecalls-imports', 'EveCalls\ImportController')
        ->except(['edit', 'update', 'destroy']);
});

Route::prefix('webhook')->group(function () {
    Route::post('contact-add', 'WebhookController@onContactAdded')
        ->name('webhook.contact.add');
    Route::post('survey', 'WebhookController@onSurveyReceived')
        ->name('webhook.survey');
});

app/Models/Site.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Site
 * @package App\Models
 */
class Site extends Model
{
    use SoftDeletes;

    public const SITE_TYPE = 0;
    public const IMPORT_TYPE = 1;

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'password',
        'publish',
        'url',
    ];

    /**
     * @var array
     */
    protected $casts = [
        'deleted_at' => 'datetime',
        'handled_at' => 'datetime',
        'project_id' => 'integer',
        'publish'    => 'boolean',
        'type'       => 'integer',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function groups()
    {
        return $this->belongsToMany(Group::class, 'group_site')
            ->orderBy('name');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function rules()
    {
        return $this->hasMany(Rule::class)
            ->with('group')
            ->where('publish', true)
            ->whereNotNull('group_id')
            ->whereHas('group', function (Builder $query) {
                $query->where('publish', true);
            })
            ->orderBy('priority');
    }
}

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Site\PublishRequest;
use App\Http\Requests\Site\StoreImportRequest;
use App\Http\Requests\Site\StoreRequest;
use App\Http\Requests\Site\UpdateImportRequest;
use App\Http\Requests\Site\UpdateRequest;
use App\Models\Application;
use App\Models\Group;
use App\Models\Import;
use App\Models\Rule;
use App\Models\Site;
use App\Models\Project;
use BadMethodCallException;
use Illuminate\Support\Arr;
use Throwable;

/**
 * Class SiteController
 * @package App\Http\Controllers
 */
class SiteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \App\Models\Project $project
     * @return \Illuminate\Contracts\View\View
     * @throws Throwable
     */
    public function index(Project $project)
    {
        if (\Gate::denies('site.list', [$project])) {
            \App::abort(403);
        }

        try {
            $sites = Site::with(['groups'])
                ->whereProjectId($project->id)
                ->orderBy('name')
                ->get();
        } catch (Throwable $exception) {
            throw $exception;
        }

        return \View::make('site.index', [
            'project' => $project,
            'sites' => $sites,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \App\Models\Project $project
     * @return \Illuminate\Contracts\View\View
     * @throws Throwable
     */
    public function create(Project $project)
    {
        if (\Gate::denies('site.create', [$project])) {
            \App::abort(403);
        }

        try {
            $groups = Group::whereProjectId($project->id)->orderBy('name')->get();
        } catch (Throwable $exception) {
            throw $exception;
        }

        return \View::make('site.create', [
            'project' => $project,
            'groups' => $groups,
        ]);
    }

    /**
     * @param Project $project
     * @return \Illuminate\Contracts\View\View
     * @throws Throwable
     */
    public function createImport(Project $project)
    {
        if (\Gate::denies('site.create', [$project])) {
            \App::abort(403);
        }

        try {
            $groups = Group::whereProjectId($project->id)->orderBy('name')->get();
        } catch (Throwable $exception) {
            throw $exception;
        }

        return \View::make('site.create_import', [
            'project' => $project,
            'groups' => $groups,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreRequest $request
     * @param  \App\Models\Project $project
     * @return \Illuminate\Http\JsonResponse
     * @throws Throwable
     */
    public function store(StoreRequest $request, Project $project)
    {
        $attributes = $request->validated();
        $groupIds = Arr::get($attributes, 'group_id', []);

        $site = new Site();
        $site->project_id = $project->id;
        $site->type = Site::SITE_TYPE;
        $site->fill($attributes);
        try {
            $site->saveOrFail();
            $site->groups()->sync($groupIds);
        } catch (Throwable $exception) {
            throw $exception;
        }

        if (\Gate::allows('site.update', [$project, $site])) {
            $redirect = \URL::route('projects.sites.edit', ['project' => $project, 'site' => $site]);
        } else {
            $redirect = \URL::route('projects.sites.create', ['project' => $project]);
        }

        return \Response::json(['redirect' => $redirect]);
    }

    /**
     * @param StoreImportRequest $request
     * @param Project $project
     * @return \Illuminate\Http\JsonResponse
     * @throws Throwable
     */
    public function storeImport(StoreImportRequest $request, Project $project)
    {
        $attributes = $request->validated();
        $groupIds = Arr::get($attributes, 'group_id', []);
        $attributes['url'] = '';
        $attributes['password'] = '';

        $site = new Site();
        $site->project_id = $project->id;
        $site->type = Site::IMPORT_TYPE;
        $site->fill($attributes);
        try {
            $site->saveOrFail();
            $site->groups()->sync($groupIds);
        } catch (Throwable $exception) {
            throw $exception;
        }

        if (\Gate::allows('site.update', [$project, $site])) {
            $redirect = \URL::route('projects.sites.edit_import', ['project' => $project, 'site' => $site]);
        } else {
            $redirect = \URL::route('projects.sites.create_import', ['project' => $project]);
        }

        return \Response::json(['redirect' => $redirect]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Project $project
     * @param  \App\Models\Site $site
     * @return void
     * @throws Throwable
     */
    public function show(Project $project, Site $site)
    {
        throw new BadMethodCallException('Method not implemented');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Project $project
     * @param  \App\Models\Site $site
     * @return \Illuminate\Contracts\View\View
     * @throws Throwable
     */
    public function edit(Project $project, Site $site)
    {
        if (\Gate::denies('site.update', [$project, $site])) {
            \App::abort(403);
        }

        if ($site->project_id !== $project->id || $site->type !== Site::SITE_TYPE) {
            \App::abort(404);
        }

        try {
            $groups = Group::whereProjectId($project->id)->orderBy('name')->get();
        } catch (Throwable $exception) {
            throw $exception;
        }

        return \View::make('site.edit', [
            'project' => $project,
            'site' => $site,
            'groups' => $groups,
        ]);
    }

    /**
     * @param Project $project
     * @param Site $site
     * @return \Illuminate\Contracts\View\View
     * @throws Throwable
     */
    public function editImport(Project $project, Site $site)
    {
        if (\Gate::denies('site.update', [$project, $site])) {
            \App::abort(403);
        }

        if ($site->project_id !== $project->id || $site->type !== Site::IMPORT_TYPE) {
            \App::abort(404);
        }

        try {
            $groups = Group::whereProjectId($project->id)->orderBy('name')->get();
        } catch (Throwable $exception) {
            throw $exception;
        }

        return \View::make('site.edit_import', [
            'project' => $project,
            'site' => $site,
            'groups' => $groups,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param  \App\Models\Project $project
     * @param  \App\Models\Site $site
     * @return \Illuminate\Http\JsonResponse|null
     * @throws Throwable
     */
    public function update(UpdateRequest $request, Project $project, Site $site)
    {
        if ($site->project_id !== $project->id || $site->type !== Site::SITE_TYPE) {
            \App::abort(404);
        }

        $attributes = $request->validated();
        $groupIds = Arr::get($attributes, 'group_id', []);
        if (! is_string($attributes['password'])) {
            unset($attributes['password']);
        }

        try {
            $site->update($attributes);
            $site->groups()->sync($groupIds);
        } catch (Throwable $exception) {
            throw $exception;
        }

        if ($project->publish) {
            return null;
        }

        $redirect = \URL::route('projects.sites.edit', ['project' => $project, 'site' => $site]);

        return \Response::json(['redirect' => $redirect]);
    }

    /**
     * @param UpdateImportRequest $request
     * @param Project $project
     * @param Site $site
     * @return \Illuminate\Http\JsonResponse|null
     * @throws Throwable
     */
    public function updateImport(UpdateImportRequest $request, Project $project, Site $site)
    {
        if ($site->project_id !== $project->id || $site->type !== Site::IMPORT_TYPE) {
            \App::abort(404);
        }

        $attributes = $request->validated();
        $groupIds = Arr::get($attributes, 'group_id', []);

        try {
            $site->update($attributes);
            $site->groups()->sync($groupIds);
        } catch (Throwable $exception) {
            throw $exception;
        }

        if ($project->publish) {
            return null;
        }

        $redirect = \URL::route('projects.sites.edit_import', ['project' => $project, 'site' => $site]);

        return \Response::json(['redirect' => $redirect]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Project $project
     * @param  \App\Models\Site $site
     * @return void
     * @throws Throwable
     */
    public function destroy(Project $project, Site $site)
    {
        if (\Gate::denies('site.delete', [$project, $site])) {
            \App::abort(403);
        }

        if ($site->project_id !== $project->id) {
            abort(404);
        }

        try {
            $siteIds = Application::select(['site_id'])
                ->distinct('site_id')
                ->getQuery()
                ->pluck('site_id');
            $isUsed = $siteIds->contains($site->id);

            if (! $isUsed) {
                $siteIds = Import::select(['site_id'])
                    ->distinct('site_id')
                    ->getQuery()
                    ->pluck('site_id');
                $isUsed = $siteIds->contains($site->id);
            }

            if ($isUsed) {
                Rule::whereSiteId($site->id)->delete();

                $site->publish = false;
                $site->saveOrFail();
                $site->delete();
            } else {
                $site->forceDelete();
            }
        } catch (Throwable $exception) {
            throw $exception;
        }
    }

resources/views/site/create.blade.php
<?php
/** @var \App\Models\Project $project */
/** @var \Illuminate\Database\Eloquent\Collection|\App\Models\Group[] $groups */
?>

@extends('layouts.sidebar', ['project' => $project])

@section('sidebar.title')Создание сайта@endsection

@section('sidebar.breadcrumbs')
    <li class="breadcrumb-item">
        @can('site.list', [$project])
            <a href="{{ route('projects.sites.index', ['project' => $project]) }}">Сайты</a>
        @else
            <span class="text-white-50">Сайты</span>
        @endcan
    </li>
    <li class="breadcrumb-item active" aria-current="page">Создание сайта</li>
@endsection

@section('sidebar.content')
    <div class="content-header">
        <h3>Создание сайта</h3>
    </div>
    <div class="content-form">
        <form id="admin-form" action="{{ route('projects.sites.store', ['project' => $project]) }}" method="post">
            <div class="form-group row">
                <label for="name-input" class="col-sm-2 col-form-label">Название</label>
                <div class="col-sm-10">
                    <input type="text" name="name" id="name-input" class="form-control" placeholder="Введите название сайта">
                </div>
            </div>
            <div class="form-group row">
                <label for="url-input" class="col-sm-2 col-form-label">URL</label>
                <div class="col-sm-10">
                    <input type="text" name="url" id="url-input" class="form-control" placeholder="Введите URL">
                </div>
            </div>
            <div class="form-group row">
                <label for="password-input" class="col-sm-2 col-form-label">Пароль</label>
                <div class="col-sm-10">
                    <input type="password" name="password" id="password-input" class="form-control" placeholder="Введите пароль">
                </div>
            </div>
            <fieldset class="form-group">
                <div class="row">
                    <legend class="col-form-label col-sm-2 pt-0">Группы</legend>
                    <div class="col-sm-10">
                        @foreach($groups as $group)
                            <div class="form-check">
                                <input type="checkbox"
                                       name="group_id[{{ $group->id }}]"
                                       value="{{ $group->id }}"
                                       id="group_id-{{ $group->id }}-input"
                                       class="form-check-input">
                                <label class="form-check-label @if($group->publish) text-primary @else text-secondary @endif"
                                       for="group_id-{{ $group->id }}-input">{{ $group->name }}</label>
                            </div>
                        @endforeach
                    </div>
                </div>
            </fieldset>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="publish-input">Состояние</label>
                <div class="col-sm-10">
                    <input type="hidden" name="publish" value="0">
                    <input type="checkbox"
                           name="publish"
                           value="1"
                           id="publish-input"
                           class="status-change">
                    <label class="form-control" for="publish-input"></label>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Создать</button>
                    @can('site.list', [$project])
                        <a href="{{ route('projects.sites.index', ['project' => $project]) }}" class="btn">Отмена</a>
                    @else
                        <span class="btn disabled">Отмена</span>
                    @endcan
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/site/edit.blade.php
<?php
/** @var \App\Models\Project $project */
/** @var \App\Models\Site $site */
/** @var \Illuminate\Database\Eloquent\Collection|\App\Models\Group[] $groups */
?>

@extends('layouts.sidebar', ['project' => $project])

@section('sidebar.title')Редактирование сайта@endsection

@section('sidebar.breadcrumbs')
    <li class="breadcrumb-item">
        @can('site.list', [$project])
            <a href="{{ route('projects.sites.index', ['project' => $project]) }}">Сайты</a>
        @else
            <span class="text-white-50">Сайты</span>
        @endcan
    </li>
    <li class="breadcrumb-item active" aria-current="page">Редактирование сайта</li>
@endsection

@section('sidebar.content')
    <div class="content-header">
        <h3>
            Редактирование сайта &quot;<strong>{{ $site->name }}</strong>&quot;
        </h3>
    </div>
    <div class="content-form">
        <form id="admin-form" action="{{ route('projects.sites.update', ['project' => $project, 'site' => $site]) }}" method="post">
            @method('put')
            <div class="form-group row">
                <label for="name-input" class="col-sm-2 col-form-label">Название</label>
                <div class="col-sm-10">
                    <input type="text" name="name" value="{{ $site->name }}" id="name-input" class="form-control" placeholder="Введите новое название сайта">
                </div>
            </div>
            <div class="form-group row">
                <label for="url-input" class="col-sm-2 col-form-label">URL</label>
                <div class="col-sm-10">
                    <input type="text" name="url" value="{{ $site->url }}" id="url-input" class="form-control" placeholder="Введите новый URL">
                </div>
            </div>
            <div class="form-group row">
                <label for="password-input" class="col-sm-2 col-form-label">Пароль</label>
                <div class="col-sm-10">
                    <input type="password" name="password" id="password-input" class="form-control" placeholder="Введите новый пароль">
                </div>
            </div>
            <fieldset class="form-group">
                <div class="row">
                    <legend class="col-form-label col-sm-2 pt-0">Группы</legend>
                    <div class="col-sm-10">
                        @foreach($groups as $group)
                            <div class="form-check">
                                <input type="checkbox"
                                       name="group_id[{{ $group->id }}]"
                                       value="{{ $group->id }}"
                                       id="group_id-{{ $group->id }}-input"
                                       class="form-check-input"
                                       @if($site->groups->contains($group)) checked @endif>
                                <label class="form-check-label @if($group->publish) text-primary @else text-secondary @endif"
                                       for="group_id-{{ $group->id }}-input">{{ $group->name }}</label>
                            </div>
                        @endforeach
                    </div>
                </div>
            </fieldset>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="publish-input">Состояние</label>
                <div class="col-sm-10">
                    <input type="hidden" name="publish" value="0">
                    <input type="checkbox"
                           name="publish"
                           value="1"
                           id="publish-input"
                           class="status-change"
                           @if($site->publish) checked @endif>
                    <label class="form-control" for="publish-input"></label>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Изменить</button>
                    @can('site.list', [$project])
                        <a href="{{ route('projects.sites.index', ['project' => $project]) }}" class="btn">Отмена</a>
                    @else
                        <span class="btn disabled">Отмена</span>
                    @endcan
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/site/index.blade.php
<?php
/** @var \App\Models\Project $project */
/** @var \Illuminate\Database\Eloquent\Collection|\App\Models\Site[] $sites */
?>

@extends('layouts.sidebar', ['project' => $project])

@section('sidebar.title')Сайты@endsection

@section('sidebar.breadcrumbs')
    <li class="breadcrumb-item active" aria-current="page">Сайты</li>
@endsection

@section('sidebar.content')
    <div class="content-header">
        <h3>Список сайтов</h3>
        <div class="dropdown">
            @can('site.create', [$project])
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Добавить</button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{{ route('projects.sites.create', ['project' => $project]) }}" class="dropdown-item">Сайт</a>
                    <a href="{{ route('projects.sites.create_import', ['project' => $project]) }}" class="dropdown-item">Импорт</a>
                </div>
            @else
                <button type="button" class="btn btn-secondary dropdown-toggle" disabled>Добавить</button>
            @endcan
        </div>
    </div>
    <div class="content-table">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Состояние</th>
                <th scope="col">Название</th>
                <th scope="col">Группы</th>
                <th scope="col">Тип</th>
                <th scope="col">ID</th>
                <th scope="col">Действия</th>
            </tr>
            </thead>
            <tbody>
                @foreach($sites as $site)
                    <tr id="site-{{ $site->id }}">
                        <td>
                            @can('site.update', [$project, $site])
                                <input type="checkbox"
                                       id="site-publish-{{ $site->id }}"
                                       class="status-change ajax"
                                       data-url="{{ route('projects.sites.publish', ['project' => $project, 'site' => $site]) }}"
                                       @if($site->publish) checked @endif>
                                <label class="ajax" for="site-publish-{{ $site->id }}" data-name="{{ $site->name }}"></label>
                            @else
                                <input type="checkbox"
                                       id="site-publish-{{ $site->id }}"
                                       class="status-change"
                                       disabled
                                       @if($site->publish) checked @endif>
                                <label for="site-publish-{{ $site->id }}"></label>
                            @endcan
                        </td>
                        <td>
                            @can('rule.list', [$site])
                                <a href="{{ route('sites.rules.index', ['site' => $site]) }}">{{ $site->name }}</a>
                            @else
                                <span class="text-secondary">{{ $site->name }}</span>
                            @endcan
                        </td>
                        <td>
                            @foreach ($site->groups as $group)
                                <span class="p-1 @if($group->publish) bg-primary @else bg-secondary @endif text-white">{{ $group->name }}</span>
                            @endforeach
                        </td>
                        <td>
                            @if($site->type === \App\Models\Site::SITE_TYPE)
                                <span class="badge badge-success">Сайт</span>
                            @elseif($site->type === \App\Models\Site::IMPORT_TYPE)
                                <span class="badge badge-warning">Импорт</span>
                            @else
                                <span class="badge badge-danger">
                                    <i class="fas fa-exclamation-triangle fa-lg"></i>
                                    Неопределён
                                    <i class="fas fa-exclamation-triangle fa-lg"></i>
                                </span>
                            @endif
                        </td>
                        <th scope="row">{{ $site->id }}</th>
                        <td>
                            <div class="btn-group" role="group">
                                @can('site.update', [$project, $site])
                                    @if($site->type === \App\Models\Site::SITE_TYPE)
                                        <a href="{{ route('projects.sites.edit', ['project' => $project, 'site' => $site]) }}" class="btn btn-outline-primary">
                                            <i class="far fa-edit"></i>
                                        </a>
                                    @elseif($site->type === \App\Models\Site::IMPORT_TYPE)
                                        <a href="{{ route('projects.sites.edit_import', ['project' => $project, 'site' => $site]) }}" class="btn btn-outline-primary">
                                            <i class="far fa-edit"></i>
                                        </a>
                                    @else
                                        <span class="btn btn-outline-secondary disabled">
                                            <i class="far fa-edit"></i>
                                        </span>
                                    @endif
                                @else
                                    <span class="btn btn-outline-secondary disabled">
                                        <i class="far fa-edit"></i>
                                    </span>
                                @endcan

                                @can('site.delete', [$project, $site])
                                    <button type="button"
                                            class="btn btn-outline-danger ajax-delete"
                                            data-url="{{ route('projects.sites.destroy', ['project' => $project, 'site' => $site]) }}"
                                            data-target="#site-{{ $site->id }}"
                                            data-name="{{ $site->name }}">
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                @else
                                    <button type="button" class="btn btn-outline-secondary" disabled>
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                @endcan
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection