routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** @noinspection PhpUndefinedMethodInspection */
Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')
        ->name('home');

    /** @noinspection PhpUndefinedMethodInspection */
    Route::name('authorization')
        ->prefix('authorization')
        ->group(function () {
            Route::get('/', 'AuthorizationController@index');
            Route::get('{crm}', 'AuthorizationController@show')->name('.show');
            Route::get('{crm}/start', 'AuthorizationController@start')->name('.start');
            Route::get('{crm}/finish', 'AuthorizationController@finish')->name('.finish');
        });

    Route::resource('projects', 'ProjectController')
        ->except('show');
    Route::patch('projects/{project}/publish', 'ProjectController@publish')
        ->name('projects.publish');
    Route::get('projects/crm/{crm}', 'ProjectController@crm');

    Route::resource('projects.sites', 'SiteController')
        ->except('show');
    Route::patch('projects/{project}/sites/{site}/publish', 'SiteController@publish')
        ->name('projects.sites.publish');
    Route::match(['get', 'head'], 'projects/{project}/sites/import/create', 'SiteController@createImport')
        ->name('projects.sites.create_import');
    Route::post('projects/{project}/sites/import', 'SiteController@storeImport')
        ->name('projects.sites.store_import');
    Route::match(['get', 'head'], 'projects/{project}/sites/import/{site}/edit', 'SiteController@editImport')
        ->name('projects.sites.edit_import');
    Route::match(['put', 'patch'], 'projects/{project}/sites/import/{site}', 'SiteController@updateImport')
        ->name('projects.sites.update_import');

    Route::resource('projects.groups', 'GroupController')
        ->except('show');
    Route::patch('projects/{project}/groups/{group}/publish', 'GroupController@publish')
        ->name('projects.groups.publish');

    Route::resource('projects.applications', 'ApplicationController')
        ->only('index', 'show');

    Route::resource('projects.managers', 'ManagerController')
        ->except('show');
    Route::patch('projects/{project}/managers/{manager}/publish', 'ManagerController@publish')
        ->name('projects.managers.publish');

    Route::resource('sites.rules', 'RuleController')
        ->except('show');
    Route::patch('sites/{site}/rules/{rule}/publish', 'RuleController@publish')
        ->name('sites.rules.publish');
    Route::patch('sites/{site}/rules/{rule}/reorder', 'RuleController@reorder')
        ->name('sites.rules.reorder');

    Route::resource('users', 'UserController')
        ->except('show');
    Route::patch('users/{user}/publish', 'UserController@publish')
        ->name('users.publish');

    Route::get('projects/{project}/imports/pattern', 'ImportController@pattern')
        ->name('projects.imports.pattern');
    Route::resource('projects.imports', 'ImportController')
        ->except(['edit', 'update', 'destroy']);

    Route::resource('crm', 'CRMController')
        ->except('show');
    Route::get('crm/{crm}/settings', 'CRMController@editSettings')
        ->name('crm.edit_settings');
    Route::post('crm/{crm}/settings', 'CRMController@updateSettings')
        ->name('crm.save_settings');

    Route::get('urls-comments', 'UrlsCommentsController@list')
        ->name('urls-comments.index');
    Route::get('urls-comments/add', 'UrlsCommentsController@add')
        ->name('urls-comments.add');
    Route::post('urls-comments/add', 'UrlsCommentsController@store')
        ->name('urls-comments.store');
    Route::get('urls-comments/{urlsComment}/edit', 'UrlsCommentsController@editRecord')
        ->name('urls-comments.edit');
    Route::post('urls-comments/{urlsComment}/edit', 'UrlsCommentsController@editRecordPost')
        ->name('urls-comments.update');
    Route::delete('urls-comments/{urlsComment}/delete', 'UrlsCommentsController@deleteRecord')
        ->name('urls-comments.delete');

    Route::resource('projects.evecalls-imports', 'EveCalls\ImportController')
        ->except(['edit', 'update', 'destroy']);
});

Route::prefix('webhook')->group(function () {
    Route::post('contact-add', 'WebhookController@onContactAdded')
        ->name('webhook.contact.add');
    Route::post('survey', 'WebhookController@onSurveyReceived')
        ->name('webhook.survey');
});

resources/views/layouts/altsidebar.blade.php
@extends('layouts.skeleton')

@section('skeleton.title')
    @yield('sidebar.title')
@endsection

@section('skeleton.content')

    <div class="container-fluid">
        <div class="row">
            <div class="content-menu db-blue">
                <ul>
                    <li>
                        <a href="{{ route('home') }}">Назад к проектам</a>
                    </li>
                </ul>
            </div>
            <div class="content-center">
                @yield('sidebar.content')
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/control.blade.php
@extends('layouts.skeleton')

@section('skeleton.title')
    @yield('control.title')
@endsection

@section('skeleton.content')
    <nav class="navbar navbar-expand-lg db-blue">
        <div class="navbar-nav navbar-left">
            <span class="navbar-brand">Управление</span>
            <a class="change-link" href="{{ route('projects.index') }}">Назад</a>
        </div>
        <nav class="navbar-nav mr-auto">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Управление</li>
                @yield('control.breadcrumbs')
            </ol>
        </nav>
        <nav class="navbar-nav">
            <button type="button" id="logout" class="btn btn-outline-light" data-url="{{ route('logout') }}">Выход</button>
        </nav>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="content-menu db-blue">

                @php $routeName = \Route::getCurrentRoute()->getName() @endphp

                <ul>
                    <li>
                        @if (starts_with($routeName, 'users'))
                            <span>Пользователи</span>
                        @else
                            @can('user.list')
                                <a href="{{ route('users.index') }}">Пользователи</a>
                            @else
                                <span class="text-white-50 bg-secondary">Пользователи</span>
                            @endif
                        @endcan
                    </li>

                    <li>
                        @if (starts_with($routeName, 'crm'))
                            <span>CRM</span>
                        @else
                            @can('crm.list')
                                <a href="{{ route('crm.index') }}">CRM</a>
                            @else
                                <span class="text-white-50 bg-secondary">CRM</span>
                            @endif
                        @endcan
                    </li>
                </ul>
            </div>
            <div class="content-center">
                @yield('control.content')
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/sidebar.blade.php
<?php /** @var \App\Models\Project $project */ ?>
@extends('layouts.skeleton')

@section('skeleton.title')
    @yield('sidebar.title')
@endsection

@section('skeleton.content')
    <nav class="navbar navbar-expand-lg db-blue">
        <div class="navbar-nav navbar-left">
            <span class="navbar-brand">{{ $project->name }}</span>
            <a class="change-link" href="{{ route('projects.index') }}">Сменить</a>
        </div>
        <nav class="navbar-nav mr-auto">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">{{ $project->name }}</li>
                @yield('sidebar.breadcrumbs')
            </ol>
        </nav>
        <nav class="navbar-nav">
            <button type="button" id="logout" class="btn btn-outline-light" data-url="{{ route('logout') }}">Выход</button>
        </nav>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="content-menu db-blue">

                @php $routeName = \Route::getCurrentRoute()->getName() @endphp

                <ul>
                    <li>
                        @if (starts_with($routeName, 'projects.managers'))
                            <span>Менеджеры</span>
                        @else
                            @can('manager.list', [$project])
                                <a href="{{ route('projects.managers.index', ['project' => $project]) }}">Менеджеры</a>
                            @else
                                <span class="text-white-50 bg-secondary">Менеджеры</span>
                            @endcan
                        @endif
                    </li>

                    <li>
                        @if (starts_with($routeName, 'projects.groups'))
                            <span>Группы</span>
                        @else
                            @can('group.list', [$project])
                                <a href="{{ route('projects.groups.index', ['project' => $project]) }}">Группы</a>
                            @else
                                <span class="text-white-50 bg-secondary">Группы</span>
                            @endcan
                        @endif
                    </li>

                    <li>
                        @if (starts_with($routeName, 'projects.sites') || starts_with($routeName, 'sites.rules'))
                            <span>Сайты</span>
                        @else
                            @can('site.list', [$project])
                                <a href="{{ route('projects.sites.index', ['project' => $project]) }}">Сайты</a>
                            @else
                                <span class="text-white-50 bg-secondary">Сайты</span>
                            @endcan
                        @endif
                    </li>

                    <li>
                        @if (starts_with($routeName, 'projects.applications'))
                            <span>Заявки</span>
                        @else
                            @can('application.list', [$project])
                                <a href="{{ route('projects.applications.index', ['project' => $project]) }}">Заявки</a>
                            @else
                                <span class="text-white-50 bg-secondary">Заявки</span>
                            @endcan
                        @endif
                    </li>

                    <li>
                        @if (starts_with($routeName, 'projects.imports'))
                            <span>Импорт</span>
                        @else
                            @can('import.list', [$project])
                                <a href="{{ route('projects.imports.index', ['project' => $project]) }}">Импорт</a>
                            @else
                                <span class="text-white-50 bg-secondary">Импорт</span>
                            @endcan
                        @endif
                    </li>

                    <li>
                        @if (starts_with($routeName, 'projects.evecalls-imports'))
                            <span>Импорт EVE.calls</span>
                        @else
                            @can('evecalls-import.list', [$project])
                                <a href="{{ route('projects.evecalls-imports.index', ['project' => $project]) }}">Импорт EVE.calls</a>
                            @else
                                <span class="text-white-50 bg-secondary">Импорт EVE.calls</span>
                            @endcan
                        @endif
                    </li>
                </ul>
            </div>
            <div class="content-center">
                @yield('sidebar.content')
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/skeleton.blade.php
<!DOCTYPE html>
<html lang="ru">

<head>

    <meta charset="utf-8">

    <title>Сервер распределения заявок - @yield('skeleton.title')</title>
    <meta name="description" content="">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>

    <!-- Custom Browsers Color Start -->
    <meta name="theme-color" content="#000">
    <!-- Custom Browsers Color End -->

    <link rel="stylesheet" href="{{ mix('css/main.min.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

</head>

<body>

@yield('skeleton.content')

<script src="{{ mix('js/scripts.min.js') }}"></script>

</body>
</html>

resources/views/layouts/start.blade.php
@extends('layouts.skeleton')

@section('skeleton.title')
    @yield('start.title')
@endsection

@section('skeleton.content')
    <nav class="navbar navbar-expand-lg navbar-light navbar-login">
        <div class="navbar-nav navbar-left">
            @can('authorization')
                <a class="btn btn-warning" href="{{ route('authorization') }}">Авторизация</a>
            @else
                <span class="btn btn-secondary disabled">Авторизация</span>
            @endcan
        </div>

        <div class="navbar-nav navbar-left">
            @can('horizon')
                <a href="{{ route('horizon.index', ['view' => 'dashboard']) }}" class="btn btn-success" target="_blank">Laravel Horizon</a>
            @else
                <span class="btn btn-secondary disabled">Laravel Horizon</span>
            @endcan
        </div>

        <div class="navbar-nav navbar-right">
            @can('urlscomment.list')
                <a href="{{ route('urls-comments.index') }}" class="btn btn-success">Урлы и комментарии</a>
            @else
                <span class="btn btn-secondary disabled">Урлы и комментарии</span>
            @endcan
        </div>

        <div class="navbar-right">
            @can('user.list')
                <a href="{{ route('users.index') }}" class="btn btn-primary">Управление</a>
            @elsecan('crm.list')
                <a href="{{ route('crm.index') }}" class="btn btn-primary">Управление</a>
            @else
                <span class="btn btn-secondary disabled">Управление</span>
            @endcan
        </div>

        <div class="navbar-right">

            <button type="button" id="logout" class="btn btn-danger" data-url="{{ route('logout') }}">Выход</button>
                {{--<span class="btn btn-secondary disabled">Выход</span>--}}

        </div>
    </nav>

    @yield('start.content')
@endsection